### ISSUE TITLE
[Tracker] Incorrect keys in retrieving Node information from storm db

### ISSUE THREAD

**Issue by johng** [omnilaboratory/obd#11]
```
        info := &dao.ObdNodeInfo{}
	err := db.Select(q.Eq("p2p_address", p2pAddress), q.Eq("is_online", true)).First(info)
	if err != nil {
		context.JSON(http.StatusInternalServerError, gin.H{
			"msg": "error p2pAddress",
		})
		return
	}
```

The following segment always fails with an `unknown field` error. Replacing the columns with their actual names fixed e.g `P2pAddress` fixed the issue. An alternative approach would be updating the schema in storm.

**Comment by iamgamelover** [comment]
Fixed. Thank you @johng
