### ISSUE TITLE
Support regtest

### ISSUE THREAD

**Issue by johng** [omnilaboratory/obd#12]
Currently the only supported options are testnet/mainnet. Regtest is very useful for testing locally and should be supported.

One option this can be supported is in the chain configuration for btcd. `chaincfg.Params`. There is an explicit `simnet` variable that `obd` doesn't use

https://github.com/omnilaboratory/obd/blob/3c095a765f2c80c9a248288ede6569de7e991b89/service/addrtool_hdwallet.go#L47

**Comment by neocarmack** [comment]
Is this still a pending issue? we will add Regtest soon

**Comment by johng** [comment]
Solved
